export const events = [
  {
    title: 'React Summit 2026',
    image: '/images/event1.png',
    slug: 'react-summit-2026',
    location: 'Seattle, WA',
    date: 'October 15, 2026',
    time: '9:00 AM',
  },
  {
    title: 'AI Developer Conference',
    image: '/images/event2.png',
    slug: 'ai-developer-conference',
    location: 'San Francisco, CA',
    date: 'November 3, 2026',
    time: '8:30 AM',
  },
  {
    title: 'Tech Meetup Night',
    image: '/images/event3.png',
    slug: 'tech-meetup-night',
    location: 'Austin, TX',
    date: 'July 28, 2026',
    time: '6:30 PM',
  },
  {
    title: 'Open Source Hackathon',
    image: '/images/event4.png',
    slug: 'open-source-hackathon',
    location: 'Chicago, IL',
    date: 'August 12, 2026',
    time: '10:00 AM',
  },
  {
    title: 'Design Systems Summit',
    image: '/images/event5.png',
    slug: 'design-systems-summit',
    location: 'New York, NY',
    date: 'September 22, 2026',
    time: '11:00 AM',
  },
  {
    title: 'Cloud & DevOps Expo',
    image: '/images/event6.png',
    slug: 'cloud-devops-expo',
    location: 'Denver, CO',
    date: 'December 5, 2026',
    time: '9:30 AM',
  },
];
